name: sachiel
description: A Trading Signals Platform for Cryptocurrency, Forex & More

publish_to: 'none'



version: 1.0.0+1



environment:
  sdk: ">=2.17.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter



  ####### ####### #######
  back_button_interceptor: ^6.0.1

  blur: ^3.0.0
  ####### ####### #######



  ####### ####### #######
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.5
  currency_text_input_formatter: ^2.1.7

  cloud_firestore: ^3.4.1
  cloud_functions: ^3.3.3
  ####### ####### #######



  ####### ####### #######
  firebase_core: ^1.20.0

  firebase_analytics: ^9.3.0
  firebase_crashlytics: ^2.8.6

  firebase_auth: ^3.6.0

  firebase_remote_config: ^2.0.13
  firebase_messaging: ^12.0.1
  firebase_in_app_messaging: ^0.6.0+20

  firebase_dynamic_links: ^4.3.3

  flutter_app_name: ^0.1.1
  flutter_launcher_icons:
    path: 'X:\Xlutter\Libraries\SachielProject\flutter_launcher_icons'
  flutter_native_splash: ^2.1.6


  flutter_phoenix: ^1.0.0
  flutter_slidable: ^2.0.0
  fluttertoast: ^8.0.9
  ####### ####### #######



  ####### ####### #######
  google_sign_in: ^5.4.0
  ####### ####### #######



  ####### ####### #######
  intl: ^0.17.0
  ####### ####### #######



  ####### ####### #######
  liquid_swipe: ^3.0.0
  loading_animation_widget: ^1.2.0+2
  local_auth: ^2.1.0
  lottie: ^1.4.0
  ####### ####### #######



  ####### ####### #######
  marquee: ^2.2.3
  ####### ####### #######



  ####### ####### #######
  quick_actions: ^0.6.0+11
  ####### ####### #######



  ####### ####### #######
  screenshot: ^1.2.3
  share_plus: ^4.0.10
  status_bar_control: ^3.2.1
  ####### ####### #######



  ####### ####### #######
  url_launcher: ^6.1.5
  ####### ####### #######



  ####### ####### #######
  widget_mask: ^1.0.0+0
  ####### ####### #######



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - cyborg_girl.jpg

    - logo.png
    - logo_background.png
    - logo_android.png
    - logo_ios.png

    - entry_background.jpg
    - entrance_next.png

    - next_icon.png
    - next_arrow_icon.png

    - oval_circle_shape.png

    - point_icon.png

    - rectircle_shape.png

    - share_icon.png

    - squircle_logo.png
    - squircle_shape.png

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu.ttf
    - family: Handwriting
      fonts:
        - asset: fonts/waterfall.ttf
    - family: Electric
      fonts:
        - asset: fonts/electric.ttf



flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#000000"
  #background_image: "assets/logo_background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/logo.png

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. Currently, it is only supported for Android > v12 and iOS.
  branding: assets/logo.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  branding_mode: center

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-logo_background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
  # The image parameter sets the splash screen icon image.  If this parameter is not specified,
  # the app's launcher icon will be used instead.
  # Please note that the splash screen will be clipped to a circle on the center of the screen.
  # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
  # 640 pixels in diameter.
  # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
  # 768 pixels in diameter.
  #image: assets/android12splash.png

  # App icon background color.
  #icon_background_color: "#111111"

  # The image_dark parameter and icon_background_color_dark set the image and icon background
  # color when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above.
  #image_dark: assets/android12splash-invert.png
  #icon_background_color_dark: "#eeeeee"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  android: true
  ios: true
  web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'


flutter_icons:
  image_path_android: "assets/logo_android.png"
  image_path_ios: "assets/logo_ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/logo_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/logo.png" # only



flutter_app_name:
  name: "Sachiel Signals"